"""
This file will generate json files for each of our fake mobility providers
after taking in a csv file generated by generate_trips.py

Author: David Klinger
"""

import pandas
import shapely.wkt
import json

def trip_convert(input_file,output_file):
    db = pandas.read_csv(input_file)
    db = db.fillna('')
    num_rows = db.shape[0]
    data = {}
    data['data'] = []
    for i in db.index:
        if i%5000==0:
            print("{} of {}".format(i,num_rows))
        d = db.loc[i].to_dict()
        start_loc = shapely.wkt.loads(d['start_point'])
        end_loc = shapely.wkt.loads(d['end_point'])
        d['start_point'] = {}
        d['start_point']['type'] = "Point"
        d['start_point']['coordinates'] = [start_loc.x,start_loc.y]
        d['end_point'] = {}
        d['end_point']['type'] = "Point"
        d['end_point']['coordinates'] = [end_loc.x,end_loc.y]
        if d['route']=='':
            d.pop('route',None)
        if d['sample_rate']=='':
            d.pop('sample_rate',None)
        data['data'].append(d)
    result = json.dumps(data,indent=4,separators=(',',': '))
    f = open(output_file,'w')
    f.write(result)

def availability_convert(input_file,output_file):
    db = pandas.read_csv(input_file)
    db = db.fillna('')
    num_rows = db.shape[0]
    data = {}
    data['data'] = []
    for i in db.index:
        if i%5000==0:
            print("{} of {}".format(i,num_rows))
        d = db.loc[i].to_dict()
        if d['associated_trips']=='':
            d.pop('associated_trips',None)
        if d['allowed_placement']==1:
            d['allowed_placement'] = "true"
        else:
            d['allowed_placement'] = "false"
        data['data'].append(d)
    result = json.dumps(data,indent=4,separators=(',',': '))
    f = open(output_file,'w')
    f.write(result)

print("Converting Lemon Trips")
trip_convert('lemon_trips.csv','lemon_trips.json')
print("Done.")
print("Converting Bat Trips")
trip_convert('bat_trips.csv','bat_trips.json')
print("Done.")

print("Converting Lemon Availability")
availability_convert('lemon_availability.csv','lemon_availability.json')
print("Done.")
print("Converting Bat Availability")
availability_convert('bat_availability.csv','bat_availability.json')
print("Done.")
